version: '3'

services:
  tira9-application2:
    build: 
      context: ./tira9-application2
      dockerfile: build/Dockerfile-web
      args:
          TIRA_PASSWORD: tira
    image: webis/tira9-application2:v1
    hostname: tira9-application2
    # hostname: $HOSTNAME
    environment:
      - TIRA_PASSWORD=tira
      - TIRA_FQDN=tira9-application2
    # env_file:
    # - tira9-application2.env
    ports:
      - '22:22'
    volumes:
      - /dev/vboxdrv:/dev/vboxdrv
      - /dev/vboxnetflt:/dev/vboxnetflt
      - /dev/vboxnetadp:/dev/vboxnetadp
      - /dev/vboxpci:/dev/vboxpci
      - ./initial-docker-tira-model:/mnt/nfs/tira
      - ./tira9-application2/src:/usr/lib/tira
    networks: 
      - tiranetwork
    container_name: tira9-application2
    privileged: true
    cap_add: 
      - NET_ADMIN

  tira9-client-web:
    build:
      context: ./tira9-client-web
      dockerfile: build/Dockerfile-web
    image: mam10eks/tmp-tira-mam10eks:9.0.12
    hostname: tira9-client-web
    ports:
      - '8080:8080'
    volumes:
      - ./initial-docker-tira-model:/mnt/nfs/tira
    networks: 
      - tiranetwork
    container_name: tira9-client-web

volumes:
  tira-model:

networks:
  tiranetwork:
