# --- Djangos Settings
debug: false
allowed_hosts:
  - "*"
# --- Tira specific settings
tira_root: /mnt/ceph/tira
# deployment = {disraptor, legacy}
deployment: disraptor
logging_dir: /mnt/ceph/tira/log/tira-application
# in the legacy deployment, a path to the users file is needed
# legacy_users_file: /mnt/ceph/tira/model/users/users.prototext
# grpc_host can be local or remote. If local, it will call localhost (i.e. for testing). If remote, it will call the vm-host
grpc_host: remote
grpc_server_port: 50051
