# ---
debug: true
allowed_hosts:
  - "127.0.0.1"
# ---
tira_root: /mnt/ceph/tira
# deployment = {disraptor, legacy}
deployment: disraptor
# in the legacy deployment, a path to the users file is needed
legacy_users_file: /mnt/ceph/tira/model/users/users.prototext