# ---
debug: true
allowed_hosts:
  - "127.0.0.1"
django_secret: 'not-so-secret'
# ---
tira_root: /mnt/ceph/tira
# deployment = {disraptor, legacy}
deployment: legacy
# in the legacy deployment, a path to the users file is needed
legacy_users_file: /mnt/ceph/tira/model/users/users.prototext
logging_dir: /mnt/ceph/tira/log/tira-application
# grpc_host can be local or remote. If local, it will call localhost (i.e. for testing). If remote, it will call the vm-host
# When developing, set this option to local, otherwise you might accidentally remote-control the live-vms.
grpc_host: local
host_grpc_port: 50051
application_grpc_port: 50052