# --- Djangos Settings
debug: false
allowed_hosts:
  - "*"
# --- Tira specific settings
tira_root: /mnt/ceph/tira
# deployment = {disraptor, legacy}
deployment: disraptor
# in the legacy deployment, a path to the users file is needed
# legacy_users_file: /mnt/ceph/tira/model/users/users.prototext
grpc_port: 50051
