apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discourse-postgres-data-pvc
  labels:
    app: tira-discourse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
