apiVersion: v1
kind: Service
metadata:
  name: tira-web-client-2
spec:
  type: NodePort
  selector:
    app: tira-web-client-2
  ports:
    - nodePort: 30808
      port: 80
      targetPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tira-web-client-2
spec:
  selector:
    matchLabels:
      app: tira-web-client-2
  replicas: 1
  template:
    metadata:
      labels:
        app: tira-web-client-2
    spec:
      containers:
      - name: tira-web-client-2
        image: webis/tira-web-2:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/mnt/ceph/tira"
          name: tira-cephfs
          readOnly: true
        - mountPath: "/tira/tira-application/src/config/settings-deploy.yml"
          name: config-yml
          subPath: settings-deploy.yml
      volumes:
      - name: tira-cephfs
        hostPath:
          path: /mnt/ceph/tira
          type: Directory
      - name: config-yml
        configMap:
          name: tira-web2-config

