apiVersion: v1
kind: Service
metadata:
  name: tira-application
  namespace: services-tira
spec:
  selector:
    app: tira-application
  ports:
  - name: ui
    port: 80
    protocol: TCP
    targetPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: tira-application-grpc-server
  namespace: services-tira
spec:
  type: NodePort
  selector:
    app: tira-application
  ports:
  - name: port-grpc-server
    nodePort: 31553
    port: 50052
    targetPort: 50052
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tira-application
  namespace: services-tira
spec:
  selector:
    matchLabels:
      app: tira-application
  replicas: 1
  template:
    metadata:
      labels:
        app: tira-application
    spec:
      containers:
      - name: tira-application
        image: registry.webis.de/code-lib/public-images/tira-application:0.0.7
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/mnt/ceph/tira"
          name: tira-cephfs
        - mountPath: "/tira/tira-application/src/config/settings-deploy.yml"
          name: config-yml
          subPath: settings-deploy.yml
        - mountPath: "/etc/discourse/client-api-key"
          name: tira-discourse-api-key
          subPath: key
        env:
          - name: DISRAPTOR_APP_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: disraptor-app-secret-key
                key: disraptor-app-secret-key
      volumes:
      - name: tira-cephfs
        cephfs:
          monitors:
            - ceph.dw.webis.de
          path: /tira
          user: tira
          secretFile: "/etc/ceph/ceph.client.tira.secret"
          readOnly: false
      - name: tira-discourse-api-key
        secret:
          secretName: tira-discourse-api-key
      - name: config-yml
        configMap:
          name: tira-application-config

