apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discourse-prod-data-pvc
  namespace: services-tira
  labels:
    app: tira-discourse-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ceph-rbd
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discourse-prod-log-pvc
  namespace: services-tira
  labels:
    app: tira-discourse-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
