on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        run: |
          cd application
          echo running on branch ${GITHUB_REF##*/}
          docker build --tag webis/tira-application:build-from-branch-${GITHUB_REF##*/} -f Dockerfile.application ..

